language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
    - sudo pecl install mongo
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer install -n

services: mongodb

script: phpunit -c app
