language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install -n --prefer-source

services: mongodb

script: phpunit -c app
