imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    fragments: { path: /_fragment }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: ::hinclude.html.twig
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    assets:
        main_css:
            inputs: [%kernel.root_dir%/Resources/public/style.css]
            filters:
                - cssrewrite
            output: css/style.css
        holder_js:
            inputs: [%kernel.root_dir%/../vendor/twbs/bootstrap/docs-assets/js/holder.js]
            output: js/holder.js
    filters:
        less:
            node: /home/spolischook/local/bin/node
            node_paths: [/home/spolischook/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

doctrine_mongodb:
    connections:
        default:
            server: mongodb://%database_host%:%database_port%
            options: {}
    default_database: %database_name%
    document_managers:
        default:
            auto_mapping: true

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: GeekHub\UserBundle\Document\User

braincrafted_bootstrap:
    less_filter: less

sensio_framework_extra:
    request: { converters: true }
    view:    { annotations: false }
    router:  { annotations: true }

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    body_converter:
        enabled: true
        validate: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: force

nelmio_api_doc: ~

liip_imagine:
    filter_sets:
        dream_list:
            quality: 75
            filters:
                thumbnail: { size: [340, 190], mode: outbound }
        user_avatar_small:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
